### ISSUE TITLE
Sharpen does not support VS 2019 but is listed on VS Marketplace under that version

### ISSUE THREAD

**Issue by MC01DA** [sharpenrocks/Sharpen#19] opened 2018-12-19 17:23 UTC
Sharpen should appear only under the version 2017. Both in the search and on the Sharpen page it is listed under 2017 and 2019 which is wrong.

**Comment by ironcev** [comment] 2019-01-14 01:17
Hi @MC01DA, Sorry for me reacting so late to this issue :-( It caught me on a pretty crazy trip (https://twitter.com/ironcev_/status/1082806302928261120) where I had very less chance to take a look at Sharpen :-(

I saw the original description, it was about an issue at install. 2019 is not supported at the moment for sure, but the installation should work with all the 2017 versions.

You have changed the title to "Del" which I interpret as "Delete". Does that mean that the issue is not there anymore? Or should I still take a look? Please let me know.

Ensuring that the installation works and that the extension is stable is one of my major priorities so I am very grateful to you for pointing out the issue.

**Comment by MC01DA** [comment] 2019-01-14 03:02
My final conclusion was that Sharpen is not supported for VS2019, So I changed title and description to Del, so I don't bother you.

But one suggestion:
![image](https://user-images.githubusercontent.com/30335051/51094898-660c9500-17b9-11e9-9dfc-e1a31b4bb832.png)

Can Sharpen version be changed to VS2017 only, so other people don't come across this problem.

**Comment by ironcev** [comment] 2019-01-14 11:11
You do not bother at all, on the contrary! This is a bug actually. Sharpen should appear only under the version 2017. Both in the search and on the Sharpen page it is listed under 2017 and 2019 which is wrong.

![image](https://user-images.githubusercontent.com/4142833/51109303-24014480-17f5-11e9-82c3-88f8913ae460.png)

I'll change the issue title and the description since this is a bug. Only, I have to see if it makes sense to fix it separately because the 2019 support is anyhow planned for the next release.

Thanks once again for reporting the issue!

**Comment by LeoJHarris** [comment] 2019-01-30 22:05
Hi @ironcev

I tried installing into VS2019 but was giving me a dependency alert: Visual Studio MPF 15.0, this is despite the fact I already have Visual Studio MPF 16.0 which I checked in the C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Platform\Visual Studio MPF directory.

Is there reason why it wont accept v16.0?

**Comment by ironcev** [comment] 2019-01-31 10:18
Hi @LeoJHarris,

Thanks for the additional input! There are several reasons why Sharpen will not work with VS 2019. The next version will be compatible with 2019, I am working on it at the moment. This should also solve this issue automatically.

The reason why it is listed on the marketplace at all is the following mistake in the `vsixmanifest` file:

        <InstallationTarget Id="Microsoft.VisualStudio.Community" Version="[15.0,16.0]" />
        <InstallationTarget Id="Microsoft.VisualStudio.Pro" Version="[15.0,16.0)" />
        <InstallationTarget Id="Microsoft.VisualStudio.Enterprise" Version="[15.0,16.0)" />
        <InstallationTarget Id="Microsoft.VisualStudio.Premium" Version="[15.0,16.0)" />
        <InstallationTarget Id="Microsoft.VisualStudio.Ultimate" Version="[15.0,16.0)" />

As you can see, the VS Community version has the version 16.0 included (squared bracket at the end) while other VS version has it excluded as it should be.

But as I said, instead of releasing new version of Sharpen with only that being fixed, I'll try to soon publish a VS 2019 version.

Thanks once again for your additional input and please be patient a bit, VS 2019 support is coming soon!

**Comment by ironcev** [comment] 2019-02-16 08:07
Hi @MC01DA, hi @LeoJHarris,
The version that supports VS2019 can be downloaded from VSIXGallery:
http://vsixgallery.com/extension/Ironcev.Sharpen/

Can you please try to install an run it on your systems, preferably in both versions of VS? If it works properly I'll publish it on VS Marketplace and close this issue and #21.

Thank you in advance and thanks once again for opening this issue.

**Comment by MC01DA** [comment] 2019-02-16 08:40
Hi @ironcev 
Installed and tested on both VS2017 and VS1019, and everything seems to work perfectly.
Thanks

**Comment by ironcev** [comment] 2019-02-16 08:55
Thanks for the quick feedback @MC01DA :-)

**Comment by ironcev** [comment] 2019-02-17 08:14
Fixed in [Sharpen v0.8.0](https://github.com/sharpenrocks/Sharpen/releases/tag/v0.8.0).

**Closed by ironcev** 2019-02-17 08:14 UTC
Labels: bug

**Comment by ironcev** [comment] 2019-02-17 10:14
Hi @MC01DA , hi @LeoJHarris, FYI I mentioned you in the [Endgame result](https://github.com/sharpenrocks/Sharpen/wiki/Endgame-for-v0.8.0) and in the [release blog post](https://sharpen.rocks/blog/sharpen-v0.8.0-support-for-vs-2019/).

Thanks once again :-)
